import { StyleSheet } from 'react-native';

import { Palette, Fonts, Typography, Spacing, MaxContentWidth } from '@/theme/tokens';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: Palette.secondary[950],
    flex: 1,
  },
  screen: {
    backgroundColor: Palette.secondary[950],
    flex: 1,
  },
  scrollContent: {
    alignItems: 'center',
    flexGrow: 1,
    paddingBottom: 104,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
  },
  content: {
    gap: Spacing.three,
    maxWidth: Math.min(MaxContentWidth, 430),
    width: '100%',
  },
  brandBar: {
    alignItems: 'center',
    backgroundColor: 'rgba(13, 14, 18, 0.96)',
    borderColor: Palette.secondary[800],
    borderCurve: 'continuous',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 56,
    paddingHorizontal: Spacing.two,
  },
  brandLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.two,
    minWidth: 0,
  },
  avatar: {
    borderColor: Palette.primary[700],
    borderRadius: 19,
    borderWidth: 1,
    height: 38,
    width: 38,
  },
  avatarFallback: {
    alignItems: 'center',
    backgroundColor: Palette.primary[500],
    borderColor: Palette.primary[700],
    borderRadius: 19,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  avatarInitials: {
    color: Palette.secondary[950],
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  brandName: {
    ...Typography.base,
    color: Palette.white,
    fontFamily: Fonts.heading,
  },
  syncPill: {
    alignItems: 'center',
    backgroundColor: '#272525',
    borderCurve: 'continuous',
    borderRadius: 16,
    flexDirection: 'row',
    gap: Spacing.one,
    minHeight: 30,
    paddingHorizontal: Spacing.two,
  },
  syncText: {
    color: Palette.white,
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    lineHeight: 14,
  },
  cloudIcon: {
    alignItems: 'center',
    height: 14,
    justifyContent: 'center',
    width: 18,
  },
  cloudBody: {
    backgroundColor: '#1DBA66',
    borderRadius: 8,
    height: 12,
    width: 18,
  },
  cloudCheck: {
    color: Palette.secondary[950],
    fontFamily: Fonts.bodyBold,
    fontSize: 6,
    lineHeight: 8,
    position: 'absolute',
  },
  greetingBlock: {
    gap: Spacing.one,
  },
  dateLabel: {
    color: Palette.primary[400],
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
    textTransform: 'uppercase',
  },
  greeting: {
    ...Typography['3xl'],
    color: Palette.white,
    fontFamily: Fonts.heading,
    lineHeight: 34,
  },
  weekCard: {
    backgroundColor: '#1F1D1D',
    borderColor: '#343131',
    borderCurve: 'continuous',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.one,
    justifyContent: 'space-between',
    padding: Spacing.two,
  },
  dayCell: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 8,
    flex: 1,
    gap: 2,
    minHeight: 54,
    minWidth: 36,
    paddingVertical: Spacing.one,
  },
  dayCellSelected: {
    backgroundColor: Palette.primary[500],
  },
  pressed: {
    opacity: 0.68,
  },
  dayLabel: {
    color: Palette.neutral[400],
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 14,
  },
  dayDate: {
    color: Palette.white,
    fontFamily: Fonts.bodyBold,
    fontSize: 13,
    lineHeight: 18,
  },
  dayTextSelected: {
    color: Palette.secondary[950],
  },
  workoutCard: {
    backgroundColor: '#2A2828',
    borderColor: '#3B3838',
    borderCurve: 'continuous',
    borderRadius: 10,
    borderWidth: 1,
    gap: Spacing.three,
    padding: Spacing.three,
  },
  schedulePill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 95, 31, 0.14)',
    borderColor: 'rgba(255, 95, 31, 0.28)',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.one,
    minHeight: 26,
    paddingHorizontal: Spacing.two,
  },
  scheduleDot: {
    backgroundColor: Palette.primary[500],
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  scheduleText: {
    color: Palette.primary[400],
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    lineHeight: 14,
  },
  cardTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.two,
  },
  workoutCopy: {
    flex: 1,
    gap: Spacing.one,
  },
  workoutTitle: {
    ...Typography['2xl'],
    color: Palette.white,
    fontFamily: Fonts.heading,
    lineHeight: 30,
  },
  focusText: {
    color: Palette.white,
    fontFamily: Fonts.bodyMedium,
    fontSize: 13,
    lineHeight: 18,
  },
  dumbbellMark: {
    height: 58,
    transform: [{ rotate: '-45deg' }],
    width: 58,
  },
  dumbbellLine: {
    backgroundColor: Palette.primary[800],
    height: 8,
    left: 10,
    position: 'absolute',
    top: 25,
    width: 38,
  },
  dumbbellPlate: {
    backgroundColor: Palette.primary[800],
    borderRadius: 2,
    height: 21,
    position: 'absolute',
    top: 18,
    width: 7,
  },
  dumbbellPlateLeft: {
    left: 6,
  },
  dumbbellPlateRight: {
    right: 6,
  },
  dumbbellPlateFarLeft: {
    left: 16,
  },
  dumbbellPlateFarRight: {
    right: 16,
  },
  workoutMeta: {
    flexDirection: 'row',
    gap: Spacing.three,
  },
  metaItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.one,
  },
  metaText: {
    color: Palette.white,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  gridIcon: {
    borderColor: Palette.primary[500],
    borderRadius: 2,
    borderWidth: 1.5,
    height: 14,
    width: 14,
  },
  gridLineHorizontal: {
    backgroundColor: Palette.primary[500],
    height: 1.5,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 5,
  },
  gridLineVertical: {
    backgroundColor: Palette.primary[500],
    bottom: 0,
    left: 5,
    position: 'absolute',
    top: 0,
    width: 1.5,
  },
  clockIcon: {
    borderColor: Palette.primary[500],
    borderRadius: 7,
    borderWidth: 1.5,
    height: 14,
    width: 14,
  },
  clockHandTall: {
    backgroundColor: Palette.primary[500],
    height: 5,
    left: 5,
    position: 'absolute',
    top: 2,
    width: 1.5,
  },
  clockHandWide: {
    backgroundColor: Palette.primary[500],
    height: 1.5,
    left: 5,
    position: 'absolute',
    top: 6,
    width: 4,
  },
  startButton: {
    alignItems: 'center',
    backgroundColor: Palette.primary[500],
    borderCurve: 'continuous',
    borderRadius: 7,
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: Spacing.three,
  },
  startButtonPressed: {
    backgroundColor: Palette.primary[600],
    transform: [{ scale: 0.99 }],
  },
  startButtonDisabled: {
    opacity: 0.54,
  },
  playIcon: {
    color: Palette.secondary[950],
    fontFamily: Fonts.bodyBold,
    fontSize: 15,
    lineHeight: 18,
  },
  startButtonText: {
    color: Palette.secondary[950],
    fontFamily: Fonts.bodyBold,
    fontSize: 17,
    lineHeight: 22,
  },
  section: {
    gap: Spacing.two,
  },
  statusCard: {
    backgroundColor: '#1F1D1D',
    borderColor: '#343131',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: Spacing.one,
    padding: Spacing.three,
  },
  statusTitle: {
    color: Palette.white,
    fontFamily: Fonts.heading,
    fontSize: 18,
    lineHeight: 24,
  },
  statusBody: {
    color: Palette.neutral[300],
    fontFamily: Fonts.bodyMedium,
    fontSize: 13,
    lineHeight: 18,
  },
  sectionEyebrow: {
    color: Palette.primary[400],
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
    textTransform: 'uppercase',
  },
  progressGrid: {
    flexDirection: 'row',
    gap: Spacing.two,
  },
  progressCard: {
    backgroundColor: '#1F1D1D',
    borderColor: '#343131',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: Spacing.two,
    minHeight: 112,
    padding: Spacing.three,
  },
  weightCard: {
    borderLeftColor: Palette.primary[500],
    borderLeftWidth: 3,
  },
  progressLabel: {
    color: Palette.neutral[300],
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    lineHeight: 15,
  },
  progressValue: {
    ...Typography.xl,
    color: Palette.white,
    fontFamily: Fonts.heading,
    lineHeight: 26,
  },
  deltaText: {
    color: '#2AD06F',
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 14,
  },
  streakTrack: {
    backgroundColor: '#3A3737',
    borderRadius: 2,
    height: 5,
    overflow: 'hidden',
    width: '100%',
  },
  streakFill: {
    backgroundColor: Palette.primary[500],
    height: '100%',
  },
  tipCard: {
    alignItems: 'center',
    backgroundColor: '#111010',
    borderColor: '#383434',
    borderCurve: 'continuous',
    borderRadius: 9,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.three,
    padding: Spacing.three,
  },
  tipIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 95, 31, 0.12)',
    borderColor: 'rgba(255, 95, 31, 0.35)',
    borderRadius: 18,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  medalIcon: {
    color: Palette.primary[500],
    fontFamily: Fonts.bodyBold,
    fontSize: 18,
    lineHeight: 20,
  },
  tipText: {
    color: Palette.white,
    flex: 1,
    fontFamily: Fonts.bodyMedium,
    fontSize: 13,
    fontStyle: 'italic',
    lineHeight: 19,
  },
});
