import { StyleSheet } from 'react-native';

import { DesignColors, SemanticColors, Fonts, Typography, Spacing, Radius, TouchTarget, ComponentTokens, MaxContentWidth } from '@/theme/tokens';

export const styles = StyleSheet.create({
  scrollContent: {
    alignItems: 'center',
    flexGrow: 1,
    paddingBottom: 112,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
  },
  content: {
    gap: Spacing.three,
    maxWidth: Math.min(MaxContentWidth, 430),
    width: '100%',
  },
  trendBlock: {
    gap: Spacing.two,
    paddingTop: Spacing.one,
  },
  trendHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  label: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    letterSpacing: 1,
    lineHeight: 15,
    textTransform: 'uppercase',
  },
  weightRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    gap: Spacing.one,
  },
  weightValue: {
    ...Typography['2xl'],
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
    fontVariant: ['tabular-nums'],
    lineHeight: 32,
  },
  weightUnit: {
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    fontSize: 14,
    lineHeight: 18,
  },
  deltaPill: {
    backgroundColor: 'rgba(255, 95, 31, 0.16)',
    borderColor: 'rgba(255, 95, 31, 0.32)',
    borderRadius: Radius.full,
    borderWidth: 1,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.one,
  },
  deltaText: {
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 14,
  },
  chartCard: {
    backgroundColor: '#3A2119',
    borderColor: 'rgba(255, 95, 31, 0.16)',
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    minHeight: 180,
    overflow: 'hidden',
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.three,
  },
  linePlot: {
    minHeight: 112,
    position: 'relative',
  },
  trendPlot: {
    minHeight: 118,
  },
  lineSegment: {
    backgroundColor: SemanticColors.action,
    borderRadius: Radius.full,
    height: 2,
    position: 'absolute',
  },
  highlightPoint: {
    backgroundColor: SemanticColors.action,
    borderColor: DesignColors.primaryFixedDim,
    borderRadius: Radius.full,
    borderWidth: 1,
    height: 8,
    left: '49%',
    position: 'absolute',
    top: '44%',
    width: 8,
  },
  chartLabels: {
    bottom: Spacing.two,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: Spacing.three,
    position: 'absolute',
    right: Spacing.three,
  },
  chartLabel: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 9,
    lineHeight: 12,
  },
  formCard: {
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: ComponentTokens.card.borderWidth,
    gap: Spacing.three,
    padding: Spacing.three,
  },
  formTitle: {
    ...Typography.lg,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
  },
  fields: {
    gap: Spacing.two,
  },
  fieldBlock: {
    gap: Spacing.one,
  },
  inputLabel: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 13,
  },
  inputShell: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderColor: 'rgba(255, 255, 255, 0.04)',
    borderCurve: 'continuous',
    borderRadius: Radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.two,
    minHeight: 52,
    paddingHorizontal: Spacing.two,
  },
  input: {
    color: SemanticColors.textPrimary,
    flex: 1,
    fontFamily: Fonts.bodyBold,
    fontSize: 13,
    lineHeight: 18,
    minHeight: 50,
    padding: 0,
  },
  inputWithIcon: {
    color: SemanticColors.textPrimary,
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: SemanticColors.action,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'center',
    minHeight: TouchTarget.min,
  },
  addButtonPressed: {
    backgroundColor: DesignColors.inversePrimary,
    transform: [{ scale: 0.99 }],
  },
  addButtonText: {
    color: DesignColors.onPrimaryContainer,
    fontFamily: Fonts.bodyBold,
    fontSize: 15,
    lineHeight: 20,
  },
  historyBlock: {
    gap: Spacing.two,
  },
  historyHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  historyTitle: {
    ...Typography.lg,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
  },
  viewAllButton: {
    minHeight: 32,
    paddingHorizontal: Spacing.one,
    justifyContent: 'center',
  },
  viewAllText: {
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  historyList: {
    gap: Spacing.two,
  },
  historyRow: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.two,
    minHeight: 72,
    padding: Spacing.two,
  },
  historyIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 95, 31, 0.12)',
    borderColor: 'rgba(255, 95, 31, 0.24)',
    borderRadius: Radius.full,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  historyCopy: {
    flex: 1,
    gap: Spacing.half,
    minWidth: 0,
  },
  historyDate: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 13,
    lineHeight: 17,
  },
  historyWeight: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 13,
  },
  historyStats: {
    alignItems: 'flex-end',
    gap: Spacing.half,
  },
  bodyFat: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  bmi: {
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 13,
  },
  pressed: {
    opacity: 0.72,
    transform: [{ scale: 0.99 }],
  },
});
