import { StyleSheet } from 'react-native';

import { DesignColors, SemanticColors, Fonts, Typography, Spacing, Radius, ComponentTokens, MaxContentWidth } from '@/theme/tokens';

export const styles = StyleSheet.create({
  scrollContent: {
    alignItems: 'center',
    flexGrow: 1,
    paddingBottom: 112,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
  },
  content: {
    gap: Spacing.three,
    maxWidth: Math.min(MaxContentWidth, 430),
    width: '100%',
  },
  headingBlock: {
    gap: Spacing.half,
    paddingTop: Spacing.one,
  },
  eyebrow: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 13,
    lineHeight: 17,
  },
  subtitle: {
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyMedium,
    fontSize: 12,
    lineHeight: 17,
  },
  metricGrid: {
    flexDirection: 'row',
    gap: Spacing.two,
  },
  metricCard: {
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: ComponentTokens.card.borderWidth,
    flex: 1,
    gap: Spacing.one,
    minHeight: 108,
    padding: Spacing.three,
  },
  metricLabel: {
    color: SemanticColors.actionSoft,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  metricValue: {
    ...Typography.lg,
    color: SemanticColors.action,
    fontFamily: Fonts.heading,
    fontVariant: ['tabular-nums'],
    lineHeight: 25,
    paddingTop: Spacing.two,
  },
  metricHelper: {
    color: DesignColors.primaryFixedDim,
    fontFamily: Fonts.bodyMedium,
    fontSize: 12,
    lineHeight: 16,
  },
  card: {
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: ComponentTokens.card.borderWidth,
    gap: Spacing.three,
    padding: Spacing.three,
  },
  cardPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.99 }],
  },
  cardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'space-between',
  },
  cardTitle: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 13,
    lineHeight: 18,
  },
  cardAction: {
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  linePlot: {
    minHeight: 72,
    overflow: 'hidden',
    position: 'relative',
  },
  bodyPlot: {
    minHeight: 64,
  },
  lineSegment: {
    backgroundColor: SemanticColors.action,
    borderRadius: Radius.full,
    height: 2,
    position: 'absolute',
  },
  barChart: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: Spacing.three,
    justifyContent: 'space-between',
    minHeight: 168,
    paddingTop: Spacing.three,
  },
  barColumn: {
    alignItems: 'center',
    flex: 1,
    gap: Spacing.two,
    justifyContent: 'flex-end',
  },
  sessionBar: {
    backgroundColor: SemanticColors.action,
    borderRadius: Radius.sm,
    maxWidth: 42,
    minWidth: 26,
    width: '100%',
  },
  axisLabel: {
    color: SemanticColors.actionSoft,
    fontFamily: Fonts.bodyBold,
    fontSize: 9,
    lineHeight: 12,
    textTransform: 'uppercase',
  },
  volumePlot: {
    minHeight: 184,
    position: 'relative',
  },
  volumeLineLayer: {
    bottom: Spacing.three,
    left: Spacing.two,
    minHeight: 142,
    position: 'absolute',
    right: Spacing.two,
    top: Spacing.two,
  },
  plotAxisY: {
    backgroundColor: SemanticColors.border,
    bottom: Spacing.three,
    left: Spacing.two,
    position: 'absolute',
    top: Spacing.two,
    width: 1,
  },
  plotAxisX: {
    backgroundColor: SemanticColors.border,
    bottom: Spacing.three,
    height: 1,
    left: Spacing.two,
    position: 'absolute',
    right: Spacing.two,
  },
  volumeTotal: {
    color: SemanticColors.actionSoft,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    left: '32%',
    letterSpacing: 0.6,
    lineHeight: 16,
    position: 'absolute',
    textTransform: 'uppercase',
    top: '44%',
  },
  heatmapBlock: {
    flexDirection: 'row',
    gap: Spacing.two,
  },
  heatmapLabels: {
    justifyContent: 'space-around',
    paddingVertical: Spacing.half,
  },
  heatmapLabel: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 12,
  },
  heatmapGrid: {
    flex: 1,
    gap: Spacing.one,
    minWidth: 0,
  },
  heatmapRow: {
    flexDirection: 'row',
    gap: Spacing.one,
  },
  heatmapCell: {
    aspectRatio: 1,
    borderRadius: 1,
    flex: 1,
  },
  heatmapLegend: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.one,
    justifyContent: 'flex-end',
  },
  legendText: {
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyBold,
    fontSize: 9,
    lineHeight: 12,
  },
  legendCell: {
    borderRadius: 1,
    height: 10,
    width: 10,
  },
  prBadge: {
    alignItems: 'center',
    backgroundColor: DesignColors.primaryFixed,
    borderRadius: Radius.full,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  prList: {
    gap: Spacing.two,
  },
  prRow: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.two,
    minHeight: 72,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.two,
  },
  prIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 95, 31, 0.12)',
    borderRadius: Radius.sm,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  prCopy: {
    flex: 1,
    gap: Spacing.half,
    minWidth: 0,
  },
  prTitle: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 13,
    lineHeight: 18,
  },
  prDetail: {
    color: DesignColors.primaryFixedDim,
    fontFamily: Fonts.bodyMedium,
    fontSize: 11,
    lineHeight: 15,
  },
  prValueBlock: {
    alignItems: 'flex-end',
    gap: Spacing.half,
  },
  prChange: {
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  prTag: {
    color: DesignColors.primaryFixedDim,
    fontFamily: Fonts.bodyBold,
    fontSize: 9,
    lineHeight: 12,
    textTransform: 'uppercase',
  },
  pressed: {
    opacity: 0.7,
    transform: [{ scale: 0.99 }],
  },
});
