import { StyleSheet } from 'react-native';

import { DesignColors, SemanticColors, Fonts, Typography, TypeScale, Spacing, Radius, TouchTarget, MaxContentWidth } from '@/theme/tokens';

export const styles = StyleSheet.create({
  scrollContent: {
    alignItems: 'center',
    flexGrow: 1,
    paddingBottom: 112,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
  },
  content: {
    gap: Spacing.three,
    maxWidth: Math.min(MaxContentWidth, 430),
    width: '100%',
  },
  heroBlock: {
    alignItems: 'center',
    gap: Spacing.two,
    paddingTop: Spacing.one,
  },
  endedPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 95, 31, 0.14)',
    borderColor: 'rgba(255, 95, 31, 0.34)',
    borderRadius: Radius.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.one,
    minHeight: 34,
    paddingHorizontal: Spacing.three,
  },
  endedText: {
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    letterSpacing: 0.8,
    lineHeight: 15,
    textTransform: 'uppercase',
  },
  title: {
    ...TypeScale.headlineMd,
    color: SemanticColors.textPrimary,
    textAlign: 'center',
  },
  checkRing: {
    alignItems: 'center',
    borderColor: SemanticColors.action,
    borderRadius: Radius.full,
    borderWidth: 2,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  subtitle: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyMedium,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.two,
  },
  statCard: {
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: Spacing.four,
    minHeight: 136,
    padding: Spacing.three,
  },
  statCopy: {
    gap: Spacing.half,
  },
  statLabel: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    lineHeight: 14,
  },
  statValue: {
    ...Typography.xl,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
    fontVariant: ['tabular-nums'],
    lineHeight: 26,
  },
  recordCard: {
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    gap: Spacing.two,
    padding: Spacing.three,
  },
  sectionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.two,
  },
  recordTitle: {
    ...Typography.lg,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
  },
  recordDescription: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyMedium,
    fontSize: 13,
    lineHeight: 19,
  },
  prRow: {
    flexDirection: 'row',
    gap: Spacing.two,
    paddingTop: Spacing.one,
  },
  prBox: {
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    gap: Spacing.half,
    minHeight: 58,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  prBoxActive: {
    backgroundColor: 'rgba(255, 95, 31, 0.16)',
    borderColor: 'rgba(255, 95, 31, 0.35)',
  },
  prLabel: {
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 13,
  },
  prLabelActive: {
    color: SemanticColors.actionSoft,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 13,
  },
  prValue: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
    fontSize: 16,
    lineHeight: 20,
  },
  prValueActive: {
    color: SemanticColors.action,
    fontFamily: Fonts.heading,
    fontSize: 16,
    lineHeight: 20,
  },
  notesBlock: {
    gap: Spacing.two,
  },
  notesTitle: {
    ...Typography.lg,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
  },
  notesInput: {
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyMedium,
    fontSize: 13,
    lineHeight: 19,
    minHeight: 112,
    padding: Spacing.three,
  },
  actions: {
    gap: Spacing.two,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: SemanticColors.action,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'center',
    minHeight: TouchTarget.min,
  },
  saveButtonPressed: {
    backgroundColor: DesignColors.inversePrimary,
    transform: [{ scale: 0.99 }],
  },
  saveText: {
    color: DesignColors.onPrimaryContainer,
    fontFamily: Fonts.bodyBold,
    fontSize: 13,
    letterSpacing: 0.6,
    lineHeight: 18,
    textTransform: 'uppercase',
  },
  historyButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: SemanticColors.action,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'center',
    minHeight: TouchTarget.min,
  },
  historyText: {
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    fontSize: 13,
    letterSpacing: 0.6,
    lineHeight: 18,
    textTransform: 'uppercase',
  },
  chartCard: {
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    gap: Spacing.three,
    padding: Spacing.three,
  },
  chartHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  chartTitle: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    letterSpacing: 1,
    lineHeight: 16,
    textTransform: 'uppercase',
  },
  dots: {
    flexDirection: 'row',
    gap: Spacing.one,
  },
  dot: {
    backgroundColor: DesignColors.surfaceContainerHighest,
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  dotActive: {
    backgroundColor: SemanticColors.action,
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  chartPlot: {
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    minHeight: 184,
    padding: Spacing.three,
  },
  barRow: {
    alignItems: 'flex-end',
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'space-around',
    minHeight: 132,
  },
  bar: {
    borderRadius: Radius.sm,
    width: 40,
  },
  chartLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.two,
    paddingTop: Spacing.two,
  },
  chartLabel: {
    color: SemanticColors.textMuted,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 13,
    textTransform: 'uppercase',
  },
  pressed: {
    opacity: 0.7,
    transform: [{ scale: 0.99 }],
  },
});
