import { StyleSheet } from 'react-native';

import { DesignColors, SemanticColors, Fonts, Typography, TypeScale, Spacing, Space, Radius, ComponentTokens, MaxContentWidth } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: SemanticColors.canvas,
    flex: 1,
  },
  scrollContent: {
    alignItems: 'center',
    backgroundColor: SemanticColors.canvas,
    flexGrow: 1,
    paddingBottom: 116,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.three,
  },
  content: {
    gap: Spacing.three,
    maxWidth: Math.min(MaxContentWidth, 430),
    width: '100%',
  },
  searchBox: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.input.background,
    borderColor: ComponentTokens.input.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.input.radius,
    borderWidth: ComponentTokens.input.borderWidth,
    flexDirection: 'row',
    gap: Space.sm,
    minHeight: 52,
    paddingHorizontal: Spacing.three,
  },
  searchInput: {
    ...Typography.sm,
    color: SemanticColors.textPrimary,
    flex: 1,
    fontFamily: Fonts.bodyMedium,
    minHeight: 48,
    padding: 0,
  },
  filterScroll: {
    marginHorizontal: -Spacing.three,
  },
  filterContent: {
    gap: Space.sm,
    paddingHorizontal: Spacing.three,
  },
  filterChip: {
    alignItems: 'center',
    backgroundColor: SemanticColors.card,
    borderColor: SemanticColors.border,
    borderRadius: Radius.full,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 62,
    paddingHorizontal: Spacing.three,
  },
  filterChipSelected: {
    backgroundColor: SemanticColors.action,
    borderColor: SemanticColors.action,
  },
  filterText: {
    ...Typography.xs,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
  },
  filterTextSelected: {
    color: DesignColors.onPrimaryContainer,
  },
  exerciseList: {
    gap: Spacing.two,
  },
  exerciseRow: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.card.background,
    borderColor: ComponentTokens.card.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.card.radius,
    borderWidth: ComponentTokens.card.borderWidth,
    flexDirection: 'row',
    gap: Spacing.three,
    minHeight: 88,
    padding: Spacing.two,
  },
  exerciseRowSelected: {
    borderColor: SemanticColors.active,
  },
  exerciseImage: {
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    height: 58,
    width: 58,
  },
  exerciseCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  exerciseName: {
    ...Typography.sm,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
  },
  exerciseMeta: {
    ...Typography.xs,
    color: SemanticColors.actionSoft,
    fontFamily: Fonts.bodyBold,
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerHigh,
    borderRadius: Radius.full,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  addButtonSelected: {
    backgroundColor: SemanticColors.action,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.card.background,
    borderColor: ComponentTokens.card.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.card.radius,
    borderWidth: ComponentTokens.card.borderWidth,
    gap: Space.xs,
    padding: Spacing.four,
  },
  emptyTitle: {
    ...TypeScale.headlineSm,
    color: SemanticColors.textPrimary,
    textAlign: 'center',
  },
  emptyText: {
    ...Typography.sm,
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyMedium,
    textAlign: 'center',
  },
  customButton: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.card.background,
    borderColor: ComponentTokens.card.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.card.radius,
    borderWidth: ComponentTokens.card.borderWidth,
    flexDirection: 'row',
    gap: Space.sm,
    minHeight: 62,
    paddingHorizontal: Spacing.three,
  },
  customIcon: {
    alignItems: 'center',
    borderColor: SemanticColors.actionSoft,
    borderRadius: Radius.full,
    borderWidth: 2,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  customText: {
    ...Typography.sm,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
  },
  footer: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.three,
    justifyContent: 'space-between',
    paddingTop: Space.xs,
  },
  footerCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  selectedCount: {
    ...Typography.xs,
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyBold,
  },
  routineName: {
    ...Typography.sm,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
  },
  addSelectionButton: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.button.primaryBackground,
    borderCurve: 'continuous',
    borderRadius: Radius.full,
    boxShadow: '0 14px 28px rgba(255, 95, 31, 0.24)',
    justifyContent: 'center',
    minHeight: 62,
    minWidth: 174,
    paddingHorizontal: Spacing.four,
  },
  addSelectionPressed: {
    backgroundColor: DesignColors.inversePrimary,
    transform: [{ scale: 0.99 }],
  },
  addSelectionText: {
    ...Typography.lg,
    color: DesignColors.onPrimaryContainer,
    fontFamily: Fonts.bodyBold,
  },
  pressed: {
    opacity: 0.72,
  },
});
