import { StyleSheet } from 'react-native';

import { Palette, Fonts, Typography, Spacing, MaxContentWidth } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: Palette.secondary[950],
    flex: 1,
  },
  scrollContent: {
    alignItems: 'center',
    flexGrow: 1,
    paddingBottom: 112,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
  },
  content: {
    gap: Spacing.three,
    maxWidth: Math.min(MaxContentWidth, 430),
    width: '100%',
  },
  titleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.three,
    justifyContent: 'space-between',
  },
  titleCopy: {
    flex: 1,
    gap: 2,
  },
  title: {
    ...Typography['3xl'],
    color: Palette.white,
    fontFamily: Fonts.heading,
    lineHeight: 36,
  },
  routeHint: {
    color: Palette.neutral[500],
    fontFamily: Fonts.bodyMedium,
    fontSize: 10,
    lineHeight: 14,
  },
  activeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.two,
  },
  toggleTrack: {
    backgroundColor: Palette.secondary[700],
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    paddingHorizontal: 3,
    width: 50,
  },
  toggleTrackActive: {
    backgroundColor: Palette.primary[500],
  },
  toggleThumb: {
    backgroundColor: Palette.white,
    borderRadius: 11,
    height: 22,
    width: 22,
  },
  toggleThumbActive: {
    transform: [{ translateX: 22 }],
  },
  activeText: {
    color: Palette.white,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  formGroup: {
    gap: Spacing.one,
  },
  label: {
    color: Palette.primary[400],
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  nameInput: {
    ...Typography.lg,
    backgroundColor: '#111010',
    borderColor: '#3A3737',
    borderCurve: 'continuous',
    borderRadius: 7,
    borderWidth: 1,
    color: Palette.white,
    fontFamily: Fonts.heading,
    minHeight: 64,
    paddingHorizontal: Spacing.three,
  },
  descriptionInput: {
    ...Typography.sm,
    backgroundColor: '#111010',
    borderColor: '#3A3737',
    borderCurve: 'continuous',
    borderRadius: 7,
    borderWidth: 1,
    color: Palette.white,
    fontFamily: Fonts.bodyMedium,
    minHeight: 86,
    padding: Spacing.three,
  },
  exerciseHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Spacing.one,
  },
  sectionTitle: {
    ...Typography.xl,
    color: Palette.white,
    fontFamily: Fonts.heading,
  },
  exerciseCount: {
    color: Palette.primary[100],
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    lineHeight: 16,
  },
  exerciseList: {
    gap: Spacing.three,
  },
  exerciseCard: {
    backgroundColor: '#1F1D1D',
    borderColor: '#343131',
    borderCurve: 'continuous',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 148,
    overflow: 'hidden',
    padding: Spacing.three,
  },
  dragHandle: {
    alignItems: 'center',
    gap: 3,
    justifyContent: 'center',
    paddingRight: Spacing.two,
    width: 18,
  },
  dragDot: {
    backgroundColor: Palette.secondary[700],
    borderRadius: 1.5,
    height: 3,
    width: 3,
  },
  exerciseBody: {
    flex: 1,
    gap: Spacing.two,
  },
  exerciseTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  exerciseName: {
    ...Typography.xl,
    color: Palette.white,
    flex: 1,
    fontFamily: Fonts.heading,
    lineHeight: 28,
    textAlign: 'center',
  },
  metricRow: {
    flexDirection: 'row',
    gap: Spacing.two,
  },
  metricCell: {
    flex: 1,
    minWidth: 42,
  },
  metricLabel: {
    color: Palette.primary[100],
    fontFamily: Fonts.bodyBold,
    fontSize: 9,
    lineHeight: 12,
    textTransform: 'uppercase',
  },
  metricValue: {
    color: Palette.white,
    fontFamily: Fonts.bodyBold,
    fontSize: 20,
    lineHeight: 25,
  },
  metricValueAccent: {
    color: Palette.primary[500],
  },
  trashIcon: {
    height: 18,
    width: 18,
  },
  trashLid: {
    backgroundColor: Palette.secondary[700],
    height: 2,
    left: 4,
    position: 'absolute',
    top: 3,
    width: 10,
  },
  trashCan: {
    borderColor: Palette.secondary[700],
    borderRadius: 2,
    borderWidth: 1.5,
    height: 12,
    left: 5,
    position: 'absolute',
    top: 5,
    width: 8,
  },
  addExerciseCard: {
    alignItems: 'center',
    borderColor: '#3A3737',
    borderCurve: 'continuous',
    borderRadius: 10,
    borderStyle: 'dashed',
    borderWidth: 1,
    gap: Spacing.two,
    justifyContent: 'center',
    minHeight: 126,
    padding: Spacing.three,
  },
  addIconCircle: {
    alignItems: 'center',
    borderColor: Palette.primary[100],
    borderRadius: 14,
    borderWidth: 2,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  addIcon: {
    color: Palette.primary[500],
    fontFamily: Fonts.bodyBold,
    fontSize: 22,
    lineHeight: 25,
  },
  addExerciseText: {
    color: Palette.primary[100],
    fontFamily: Fonts.bodyBold,
    fontSize: 15,
    lineHeight: 20,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: Palette.primary[500],
    borderCurve: 'continuous',
    borderRadius: 9,
    boxShadow: '0 14px 28px rgba(255, 95, 31, 0.24)',
    justifyContent: 'center',
    minHeight: 62,
    paddingHorizontal: Spacing.three,
  },
  saveButtonPressed: {
    backgroundColor: Palette.primary[600],
    transform: [{ scale: 0.99 }],
  },
  saveButtonText: {
    color: Palette.secondary[950],
    fontFamily: Fonts.bodyBold,
    fontSize: 18,
    lineHeight: 24,
  },
  pressed: {
    opacity: 0.7,
  },
});
