import { StyleSheet } from 'react-native';

import { DesignColors, SemanticColors, Fonts, Typography, TypeScale, Spacing, Radius, TouchTarget, ComponentTokens, MaxContentWidth } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: SemanticColors.canvas,
    flex: 1,
  },
  scrollContent: {
    alignItems: 'center',
    flexGrow: 1,
    paddingBottom: Spacing.five,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.three,
  },
  content: {
    gap: Spacing.three,
    maxWidth: Math.min(MaxContentWidth, 430),
    width: '100%',
  },
  sessionHeader: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: ComponentTokens.card.borderWidth,
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'space-between',
    minHeight: 72,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.two,
  },
  sessionIdentity: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.two,
    minWidth: 0,
  },
  avatar: {
    borderColor: SemanticColors.action,
    borderRadius: 22,
    borderWidth: 1,
    height: 44,
    width: 44,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
  },
  sessionTitle: {
    ...TypeScale.headlineSm,
    color: SemanticColors.actionSoft,
  },
  inProgress: {
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    letterSpacing: 1.2,
    lineHeight: 14,
    textTransform: 'uppercase',
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.two,
  },
  offlineStatus: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.one,
  },
  offlineText: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  timerButton: {
    alignItems: 'center',
    borderRadius: Radius.full,
    height: TouchTarget.min,
    justifyContent: 'center',
    width: TouchTarget.min,
  },
  timeCard: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 88,
    padding: Spacing.three,
  },
  smallLabel: {
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  timeValue: {
    ...TypeScale.headlineMd,
    color: SemanticColors.textPrimary,
    fontVariant: ['tabular-nums'],
  },
  activePill: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerHigh,
    borderRadius: Radius.full,
    flexDirection: 'row',
    gap: Spacing.one,
    minHeight: 32,
    paddingHorizontal: Spacing.three,
  },
  activeDot: {
    backgroundColor: SemanticColors.action,
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  activeText: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  exerciseCard: {
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    gap: Spacing.three,
    padding: Spacing.three,
  },
  exerciseHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'space-between',
  },
  exerciseTitleBlock: {
    flex: 1,
  },
  exerciseTitle: {
    ...TypeScale.headlineSm,
    color: SemanticColors.textPrimary,
  },
  exerciseMeta: {
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  infoButton: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerHigh,
    borderColor: SemanticColors.border,
    borderRadius: Radius.full,
    borderWidth: 1,
    height: TouchTarget.min,
    justifyContent: 'center',
    width: TouchTarget.min,
  },
  setList: {
    gap: Spacing.two,
  },
  completedSetRow: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    flexDirection: 'row',
    gap: Spacing.two,
    minHeight: 64,
    paddingHorizontal: Spacing.two,
  },
  setNumber: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerHigh,
    borderRadius: Radius.full,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  setNumberText: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 15,
    lineHeight: 20,
  },
  setValue: {
    color: SemanticColors.textPrimary,
    flex: 1,
    fontFamily: Fonts.bodyMedium,
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
  },
  setCheckButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 95, 31, 0.42)',
    borderRadius: Radius.md,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  setCheckButtonInactive: {
    backgroundColor: DesignColors.surfaceContainerHigh,
  },
  currentSetRow: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderColor: SemanticColors.action,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.two,
    minHeight: 64,
    paddingHorizontal: Spacing.two,
  },
  currentSetNumber: {
    alignItems: 'center',
    backgroundColor: SemanticColors.action,
    borderRadius: Radius.full,
    height: 36,
    justifyContent: 'center',
    width: 30,
  },
  currentSetNumberText: {
    color: DesignColors.onPrimaryContainer,
    fontFamily: Fonts.bodyBold,
    fontSize: 15,
    lineHeight: 20,
  },
  currentInput: {
    backgroundColor: DesignColors.inputBackground,
    borderCurve: 'continuous',
    borderRadius: Radius.sm,
    color: SemanticColors.textPrimary,
    flex: 1,
    fontFamily: Fonts.bodyBold,
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: Spacing.two,
    textAlign: 'center',
  },
  multiplyText: {
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyBold,
    fontSize: 16,
    lineHeight: 22,
  },
  currentToggle: {
    alignItems: 'center',
    backgroundColor: DesignColors.inputBackground,
    borderColor: DesignColors.primaryFixed,
    borderRadius: Radius.sm,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    width: 34,
  },
  currentToggleDone: {
    backgroundColor: SemanticColors.action,
    borderColor: SemanticColors.action,
  },
  restCard: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.three,
    minHeight: 132,
    padding: Spacing.three,
  },
  restRing: {
    alignItems: 'center',
    borderColor: DesignColors.surfaceContainerHighest,
    borderRadius: Radius.full,
    borderWidth: 8,
    height: 96,
    justifyContent: 'center',
    width: 96,
  },
  restLabel: {
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    letterSpacing: 0.8,
    lineHeight: 16,
    textTransform: 'uppercase',
  },
  restTime: {
    ...Typography['2xl'],
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
    fontVariant: ['tabular-nums'],
    lineHeight: 30,
  },
  restActions: {
    flex: 1,
    gap: Spacing.two,
  },
  addRestButton: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerHigh,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    justifyContent: 'center',
    minHeight: TouchTarget.min,
  },
  addRestText: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 14,
    lineHeight: 20,
    textTransform: 'uppercase',
  },
  skipRestButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: SemanticColors.action,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: TouchTarget.min,
  },
  skipRestText: {
    color: SemanticColors.actionSoft,
    fontFamily: Fonts.bodyBold,
    fontSize: 14,
    lineHeight: 20,
    textTransform: 'uppercase',
  },
  lockedCard: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLow,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 88,
    opacity: 0.72,
    padding: Spacing.three,
  },
  lockedTitle: {
    ...TypeScale.headlineSm,
    color: SemanticColors.textMuted,
  },
  lockedMeta: {
    color: SemanticColors.textMuted,
    fontFamily: Fonts.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  bottomActions: {
    flexDirection: 'row',
    gap: Spacing.two,
    paddingBottom: Spacing.two,
  },
  nextButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: SemanticColors.action,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    flex: 0.92,
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'center',
    minHeight: 64,
    paddingHorizontal: Spacing.two,
  },
  nextButtonText: {
    color: SemanticColors.actionSoft,
    fontFamily: Fonts.bodyBold,
    fontSize: 13,
    lineHeight: 16,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  finishButton: {
    alignItems: 'center',
    backgroundColor: SemanticColors.action,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    flex: 1.42,
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'center',
    minHeight: 64,
    paddingHorizontal: Spacing.two,
  },
  finishButtonPressed: {
    backgroundColor: DesignColors.inversePrimary,
    transform: [{ scale: 0.99 }],
  },
  finishButtonText: {
    ...Typography.lg,
    color: DesignColors.onPrimaryContainer,
    fontFamily: Fonts.bodyBold,
    lineHeight: 24,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  pressed: {
    opacity: 0.72,
    transform: [{ scale: 0.99 }],
  },
});
