import { StyleSheet } from 'react-native';

import { DesignColors, SemanticColors, Fonts, Typography, TypeScale, Spacing, Space, Radius, ComponentTokens, MaxContentWidth } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: SemanticColors.canvas,
    flex: 1,
  },
  scrollContent: {
    alignItems: 'center',
    backgroundColor: SemanticColors.canvas,
    flexGrow: 1,
    paddingBottom: 112,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
  },
  content: {
    gap: Spacing.three,
    maxWidth: Math.min(MaxContentWidth, 430),
    width: '100%',
  },
  titleBlock: {
    gap: Space.xs,
  },
  title: {
    ...TypeScale.headlineMd,
    color: SemanticColors.textPrimary,
  },
  subtitle: {
    ...Typography.sm,
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyMedium,
    lineHeight: 20,
  },
  videoCard: {
    aspectRatio: 1.78,
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  videoImage: {
    height: '100%',
    width: '100%',
  },
  videoPlaceholder: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerLowest,
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  videoOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0, 0, 0, 0.34)',
  },
  videoAction: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    gap: Space.xs,
    justifyContent: 'center',
  },
  playTile: {
    alignItems: 'center',
    borderColor: SemanticColors.action,
    borderRadius: Radius.sm,
    borderWidth: 3,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  videoActionText: {
    ...Typography.xs,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    textTransform: 'uppercase',
  },
  referenceCard: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.card.background,
    borderColor: SemanticColors.border,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    borderStyle: 'dashed',
    borderWidth: 1,
    gap: Space.xs,
    justifyContent: 'center',
    minHeight: 120,
    padding: Spacing.three,
  },
  cameraWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 30,
  },
  referenceText: {
    ...Typography.xs,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
  },
  referenceHint: {
    color: SemanticColors.textMuted,
    fontFamily: Fonts.bodyBold,
    fontSize: 9,
    lineHeight: 12,
    textTransform: 'uppercase',
  },
  section: {
    gap: Spacing.three,
  },
  sectionLabel: {
    ...Typography.xs,
    color: SemanticColors.action,
    fontFamily: Fonts.bodyBold,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  inputGroup: {
    backgroundColor: ComponentTokens.input.background,
    borderColor: ComponentTokens.input.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.input.radius,
    borderWidth: ComponentTokens.input.borderWidth,
    gap: Space.xs,
    padding: Spacing.three,
  },
  inputLabel: {
    color: SemanticColors.actionSoft,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 12,
  },
  nameInput: {
    ...Typography.lg,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.heading,
    minHeight: 32,
    padding: 0,
  },
  descriptionInput: {
    ...Typography.sm,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyMedium,
    minHeight: 112,
    padding: 0,
  },
  categoryGroup: {
    backgroundColor: ComponentTokens.input.background,
    borderColor: ComponentTokens.input.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.input.radius,
    borderWidth: ComponentTokens.input.borderWidth,
    gap: Space.sm,
    padding: Spacing.three,
  },
  categoryChips: {
    gap: Space.sm,
  },
  categoryChip: {
    alignItems: 'center',
    backgroundColor: SemanticColors.card,
    borderColor: SemanticColors.border,
    borderRadius: Radius.full,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: Spacing.three,
  },
  categoryChipSelected: {
    backgroundColor: SemanticColors.action,
    borderColor: SemanticColors.action,
  },
  categoryChipText: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    lineHeight: 14,
  },
  categoryChipTextSelected: {
    color: DesignColors.onPrimaryContainer,
  },
  selectRow: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.input.background,
    borderColor: ComponentTokens.input.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.input.radius,
    borderWidth: ComponentTokens.input.borderWidth,
    flexDirection: 'row',
    gap: Spacing.three,
    minHeight: 70,
    padding: Spacing.three,
  },
  selectCopy: {
    flex: 1,
    gap: Space.xs,
  },
  selectValue: {
    ...Typography.base,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
  },
  selectIcons: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Space.sm,
  },
  statusCard: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.input.background,
    borderColor: ComponentTokens.input.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.input.radius,
    borderWidth: ComponentTokens.input.borderWidth,
    flexDirection: 'row',
    gap: Spacing.three,
    minHeight: 76,
    padding: Spacing.three,
  },
  statusCopy: {
    flex: 1,
    gap: 2,
  },
  statusTitle: {
    ...Typography.sm,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
  },
  statusSubtitle: {
    color: SemanticColors.textMuted,
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    lineHeight: 14,
  },
  switchTrack: {
    backgroundColor: DesignColors.surfaceContainerHigh,
    borderRadius: Radius.full,
    height: 30,
    justifyContent: 'center',
    paddingHorizontal: 3,
    width: 52,
  },
  switchTrackActive: {
    backgroundColor: SemanticColors.action,
  },
  switchThumb: {
    backgroundColor: SemanticColors.textPrimary,
    borderRadius: Radius.full,
    height: 24,
    width: 24,
  },
  switchThumbActive: {
    transform: [{ translateX: 22 }],
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.button.primaryBackground,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    boxShadow: '0 14px 28px rgba(255, 95, 31, 0.24)',
    flexDirection: 'row',
    gap: Space.sm,
    justifyContent: 'center',
    minHeight: 62,
    paddingHorizontal: Spacing.three,
  },
  saveButtonPressed: {
    backgroundColor: DesignColors.inversePrimary,
    transform: [{ scale: 0.99 }],
  },
  saveButtonDisabled: {
    opacity: 0.54,
  },
  saveButtonText: {
    ...Typography.lg,
    color: DesignColors.onPrimaryContainer,
    fontFamily: Fonts.bodyBold,
  },
  pressed: {
    opacity: 0.72,
  },
  statusMessage: {
    backgroundColor: ComponentTokens.card.background,
    borderColor: ComponentTokens.card.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.card.radius,
    borderWidth: ComponentTokens.card.borderWidth,
    gap: Space.xs,
    padding: Spacing.three,
  },
  statusMessageTitle: {
    ...Typography.sm,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
  },
  statusMessageBody: {
    ...Typography.xs,
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyMedium,
  },
});
