import { StyleSheet } from 'react-native';

import { DesignColors, SemanticColors, Fonts, Typography, TypeScale, Spacing, Space, Radius, ComponentTokens, MaxContentWidth } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: SemanticColors.canvas,
  },
  scrollContent: {
    alignItems: 'center',
    backgroundColor: SemanticColors.canvas,
    paddingBottom: 116,
    paddingHorizontal: Spacing.three,
  },
  content: {
    gap: Spacing.three,
    maxWidth: Math.min(MaxContentWidth, 430),
    paddingTop: Spacing.two,
    width: '100%',
  },
  heroRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.three,
    justifyContent: 'space-between',
  },
  heroCopy: {
    flex: 1,
    gap: Space.xs,
    minWidth: 0,
  },
  title: {
    ...TypeScale.headlineMd,
    color: SemanticColors.textPrimary,
  },
  subtitle: {
    ...Typography.xs,
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyMedium,
  },
  createButton: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.button.primaryBackground,
    borderCurve: 'continuous',
    borderRadius: Radius.md,
    flexDirection: 'row',
    gap: Space.xs,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: Spacing.three,
    width: 134,
  },
  createButtonText: {
    color: DesignColors.onPrimaryContainer,
    flexShrink: 1,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 12,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  searchBox: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.input.background,
    borderColor: ComponentTokens.input.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.input.radius,
    borderWidth: ComponentTokens.input.borderWidth,
    flexDirection: 'row',
    gap: Space.sm,
    minHeight: 44,
    paddingHorizontal: Spacing.three,
  },
  searchInput: {
    ...Typography.xs,
    color: SemanticColors.textPrimary,
    flex: 1,
    fontFamily: Fonts.bodyMedium,
    minHeight: 42,
    padding: 0,
  },
  filterScroll: {
    marginHorizontal: -Spacing.three,
  },
  filterContent: {
    gap: Space.sm,
    paddingHorizontal: Spacing.three,
  },
  filterChip: {
    alignItems: 'center',
    backgroundColor: SemanticColors.card,
    borderColor: SemanticColors.border,
    borderRadius: Radius.full,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 30,
    paddingHorizontal: Spacing.three,
  },
  filterChipSelected: {
    backgroundColor: SemanticColors.action,
    borderColor: SemanticColors.action,
  },
  filterText: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 10,
    lineHeight: 12,
  },
  filterTextSelected: {
    color: DesignColors.onPrimaryContainer,
  },
  cardList: {
    gap: Spacing.three,
  },
  exerciseCard: {
    backgroundColor: ComponentTokens.card.background,
    borderColor: ComponentTokens.card.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.card.radius,
    borderWidth: ComponentTokens.card.borderWidth,
    overflow: 'hidden',
  },
  exerciseImage: {
    aspectRatio: 1.9,
    backgroundColor: DesignColors.surfaceContainerLowest,
    width: '100%',
  },
  exerciseImageFallback: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: {
    padding: Spacing.three,
  },
  cardTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: Spacing.two,
    justifyContent: 'space-between',
  },
  exerciseCopy: {
    flex: 1,
    gap: Space.xs,
    minWidth: 0,
  },
  exerciseName: {
    ...Typography.sm,
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Space.xs,
  },
  tag: {
    backgroundColor: 'rgba(255, 95, 31, 0.14)',
    borderRadius: Radius.sm,
    paddingHorizontal: Space.xs,
    paddingVertical: 2,
  },
  tagText: {
    color: SemanticColors.actionSoft,
    fontFamily: Fonts.bodyBold,
    fontSize: 8,
    lineHeight: 10,
  },
  menuButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  addCustomCard: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.card.background,
    borderColor: ComponentTokens.card.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.card.radius,
    borderStyle: 'dashed',
    borderWidth: ComponentTokens.card.borderWidth,
    gap: Spacing.two,
    justifyContent: 'center',
    minHeight: 122,
    padding: Spacing.three,
  },
  addCustomIcon: {
    alignItems: 'center',
    backgroundColor: DesignColors.surfaceContainerHigh,
    borderRadius: Radius.full,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  addCustomText: {
    color: SemanticColors.textPrimary,
    fontFamily: Fonts.bodyBold,
    fontSize: 11,
    lineHeight: 14,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: ComponentTokens.card.background,
    borderColor: ComponentTokens.card.borderColor,
    borderCurve: 'continuous',
    borderRadius: ComponentTokens.card.radius,
    borderWidth: ComponentTokens.card.borderWidth,
    gap: Space.xs,
    padding: Spacing.four,
  },
  emptyTitle: {
    ...TypeScale.headlineSm,
    color: SemanticColors.textPrimary,
    textAlign: 'center',
  },
  emptyText: {
    ...Typography.sm,
    color: SemanticColors.textSecondary,
    fontFamily: Fonts.bodyMedium,
    textAlign: 'center',
  },
  pressed: {
    opacity: 0.72,
  },
});
